name: Go Build and Release

on:
  release:
    types: [published]  # Trigger when a release is published

permissions:
  contents: write  # Ensure write access for creating/updating the release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go mod download

    - name: Build the Go project
      run: go build -o ./archivist_go  # Specify the binary output location

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: go-build
        path: ./archivist_go  # Ensure this matches the binary location

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: go-build  # Download the artifact built in the previous step

    - name: Create GitHub release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.release.tag_name }}  # Use the correct tag name
        name: ${{ github.event.release.tag_name }}
        body: |
          Automated release for version ${{ github.event.release.tag_name }}.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure the token has the right permissions
